kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demoapp
  labels:
    app.kubernetes.io/instance: demoapp
spec:
  host: route-demoapp-demo-kai.apps.itz-7kgxzz.tzaas.techzone.ibm.com
  path: /
  to:
    kind: Service
    name: demoapp
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None