apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp
  labels:
    app.kubernetes.io/instance: demoapp
spec:
  rules:
  - host: route-demoapp-demo-kai.apps.itz-7kgxzz.tzaas.techzone.ibm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoapp
            port:
              number: 8080