apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp
  annotations:
    # Add any required annotations here, if needed
spec:
  rules:
  - host: route-demoapp-demo-kai.apps.itz-7kgxzz.tzaas.techzone.ibm.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demoapp
            port:
              number: 8080